name: ROS2 Build

on: [push]

jobs:
  test_docker:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:jammy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Build and test ROS 2
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: wheelchair_sensor_msgs
          target-ros2-distro: humble
          skip-tests: true