name: ROS2 Build

on: [push]

jobs:
  test_docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - docker_image: ubuntu:jammy
            ros_distribution: humble
            ros_version: 2

    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Build and test ROS 2
        if: ${{ matrix.ros_version == 2 }}
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: wheelchair_sensor_msgs
          target-ros2-distro: ${{ matrix.ros_distribution }}
          skip-tests: true